-- Tworzenie tabel
CREATE TABLE autorstwo (
    Praca NUMBER(3)  NOT NULL,
    Autor VARCHAR(30) NOT NULL
);

CREATE TABLE autorzy (
    ID     VARCHAR(30) NOT NULL PRIMARY KEY,
    Ryzyko NUMBER(1)  NOT NULL,
    Sloty  VARCHAR(4) NOT NULL
);

-- Wstawianie danych
INSERT INTO autorstwo (Praca,Autor) VALUES (1,'Schubert');
INSERT INTO autorstwo (Praca,Autor) VALUES (2,'Clemente');
INSERT INTO autorstwo (Praca,Autor) VALUES (2,'Czerwiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (2,'Lasota');
INSERT INTO autorstwo (Praca,Autor) VALUES (3,'Clemente');
INSERT INTO autorstwo (Praca,Autor) VALUES (3,'Czerwiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (3,'Lasota');
INSERT INTO autorstwo (Praca,Autor) VALUES (4,'Clemente');
INSERT INTO autorstwo (Praca,Autor) VALUES (4,'Lasota');
INSERT INTO autorstwo (Praca,Autor) VALUES (5,'Czerwiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (5,'Lasota');
INSERT INTO autorstwo (Praca,Autor) VALUES (6,'Dunin-Kęplicz');
INSERT INTO autorstwo (Praca,Autor) VALUES (6,'Szałas');
INSERT INTO autorstwo (Praca,Autor) VALUES (7,'Dunin-Kęplicz');
INSERT INTO autorstwo (Praca,Autor) VALUES (7,'Szałas');
INSERT INTO autorstwo (Praca,Autor) VALUES (8,'Dziubiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (9,'Górecki');
INSERT INTO autorstwo (Praca,Autor) VALUES (10,'Górecki');
INSERT INTO autorstwo (Praca,Autor) VALUES (10,'Paszek');
INSERT INTO autorstwo (Praca,Autor) VALUES (11,'Hofman');
INSERT INTO autorstwo (Praca,Autor) VALUES (12,'Hofman');
INSERT INTO autorstwo (Praca,Autor) VALUES (13,'Hofman');
INSERT INTO autorstwo (Praca,Autor) VALUES (14,'Janusz');
INSERT INTO autorstwo (Praca,Autor) VALUES (14,'Ślęzak');
INSERT INTO autorstwo (Praca,Autor) VALUES (15,'Karczmarz');
INSERT INTO autorstwo (Praca,Autor) VALUES (15,'Sankowski');
INSERT INTO autorstwo (Praca,Autor) VALUES (16,'Karczmarz');
INSERT INTO autorstwo (Praca,Autor) VALUES (16,'Sankowski');
INSERT INTO autorstwo (Praca,Autor) VALUES (17,'Klin');
INSERT INTO autorstwo (Praca,Autor) VALUES (18,'Klin');
INSERT INTO autorstwo (Praca,Autor) VALUES (19,'Klin');
INSERT INTO autorstwo (Praca,Autor) VALUES (20,'Charalampopoulos');
INSERT INTO autorstwo (Praca,Autor) VALUES (20,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (20,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (20,'Waleń');
INSERT INTO autorstwo (Praca,Autor) VALUES (21,'Kopczyński');
INSERT INTO autorstwo (Praca,Autor) VALUES (21,'Toruńczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (22,'Kopczyński');
INSERT INTO autorstwo (Praca,Autor) VALUES (23,'Celińska-Kopczyńska');
INSERT INTO autorstwo (Praca,Autor) VALUES (23,'Kopczyński');
INSERT INTO autorstwo (Praca,Autor) VALUES (24,'Cygan');
INSERT INTO autorstwo (Praca,Autor) VALUES (24,'Kowalik');
INSERT INTO autorstwo (Praca,Autor) VALUES (25,'Cygan');
INSERT INTO autorstwo (Praca,Autor) VALUES (25,'Kowalik');
INSERT INTO autorstwo (Praca,Autor) VALUES (26,'Kowalik');
INSERT INTO autorstwo (Praca,Autor) VALUES (26,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (26,'Wrochna');
INSERT INTO autorstwo (Praca,Autor) VALUES (27,'Kowaluk');
INSERT INTO autorstwo (Praca,Autor) VALUES (28,'Michalak');
INSERT INTO autorstwo (Praca,Autor) VALUES (28,'Skibski');
INSERT INTO autorstwo (Praca,Autor) VALUES (29,'Michalak');
INSERT INTO autorstwo (Praca,Autor) VALUES (30,'Michalak');
INSERT INTO autorstwo (Praca,Autor) VALUES (31,'Michalak');
INSERT INTO autorstwo (Praca,Autor) VALUES (32,'Mucha');
INSERT INTO autorstwo (Praca,Autor) VALUES (33,'Cygan');
INSERT INTO autorstwo (Praca,Autor) VALUES (33,'Mucha');
INSERT INTO autorstwo (Praca,Autor) VALUES (33,'Węgrzycki');
INSERT INTO autorstwo (Praca,Autor) VALUES (33,'Włodarczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (34,'Nguyen AL');
INSERT INTO autorstwo (Praca,Autor) VALUES (35,'Pacuk');
INSERT INTO autorstwo (Praca,Autor) VALUES (35,'Sankowski');
INSERT INTO autorstwo (Praca,Autor) VALUES (35,'Węgrzycki');
INSERT INTO autorstwo (Praca,Autor) VALUES (35,'Wygocki');
INSERT INTO autorstwo (Praca,Autor) VALUES (36,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (37,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (37,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (37,'Wrochna');
INSERT INTO autorstwo (Praca,Autor) VALUES (38,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (39,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (40,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (41,'Bojańczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (41,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (42,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (42,'Wrochna');
INSERT INTO autorstwo (Praca,Autor) VALUES (43,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (43,'Wrochna');
INSERT INTO autorstwo (Praca,Autor) VALUES (44,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (44,'Wrochna');
INSERT INTO autorstwo (Praca,Autor) VALUES (45,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (46,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (47,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (48,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (49,'Charalampopoulos');
INSERT INTO autorstwo (Praca,Autor) VALUES (49,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (50,'Charalampopoulos');
INSERT INTO autorstwo (Praca,Autor) VALUES (50,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (51,'Charalampopoulos');
INSERT INTO autorstwo (Praca,Autor) VALUES (51,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (52,'Rządca');
INSERT INTO autorstwo (Praca,Autor) VALUES (53,'Sankowski');
INSERT INTO autorstwo (Praca,Autor) VALUES (54,'Sankowski');
INSERT INTO autorstwo (Praca,Autor) VALUES (54,'Węgrzycki');
INSERT INTO autorstwo (Praca,Autor) VALUES (55,'Sankowski');
INSERT INTO autorstwo (Praca,Autor) VALUES (55,'Wygocki');
INSERT INTO autorstwo (Praca,Autor) VALUES (56,'Schubert');
INSERT INTO autorstwo (Praca,Autor) VALUES (57,'Skibski');
INSERT INTO autorstwo (Praca,Autor) VALUES (58,'Skrzypczak');
INSERT INTO autorstwo (Praca,Autor) VALUES (59,'Michalewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (59,'Skrzypczak');
INSERT INTO autorstwo (Praca,Autor) VALUES (60,'Ślęzak');
INSERT INTO autorstwo (Praca,Autor) VALUES (61,'Adamczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (61,'Włodarczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (62,'Clemente');
INSERT INTO autorstwo (Praca,Autor) VALUES (62,'Lasota');
INSERT INTO autorstwo (Praca,Autor) VALUES (63,'Cygan');
INSERT INTO autorstwo (Praca,Autor) VALUES (63,'Mucha');
INSERT INTO autorstwo (Praca,Autor) VALUES (63,'Sankowski');
INSERT INTO autorstwo (Praca,Autor) VALUES (64,'Czerwiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (64,'Parys');
INSERT INTO autorstwo (Praca,Autor) VALUES (65,'Czerwiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (65,'Hofman');
INSERT INTO autorstwo (Praca,Autor) VALUES (66,'Czerwiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (66,'Lasota');
INSERT INTO autorstwo (Praca,Autor) VALUES (67,'Dziembowski');
INSERT INTO autorstwo (Praca,Autor) VALUES (68,'Dziembowski');
INSERT INTO autorstwo (Praca,Autor) VALUES (69,'Dziubiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (70,'Gambin');
INSERT INTO autorstwo (Praca,Autor) VALUES (70,'Niemyska');
INSERT INTO autorstwo (Praca,Autor) VALUES (70,'Startek');
INSERT INTO autorstwo (Praca,Autor) VALUES (71,'Górecki');
INSERT INTO autorstwo (Praca,Autor) VALUES (72,'Hofman');
INSERT INTO autorstwo (Praca,Autor) VALUES (72,'Lasota');
INSERT INTO autorstwo (Praca,Autor) VALUES (73,'Iwanicki');
INSERT INTO autorstwo (Praca,Autor) VALUES (74,'Iwanicki');
INSERT INTO autorstwo (Praca,Autor) VALUES (75,'Iwanicki');
INSERT INTO autorstwo (Praca,Autor) VALUES (76,'Iwanicki');
INSERT INTO autorstwo (Praca,Autor) VALUES (77,'Janusz');
INSERT INTO autorstwo (Praca,Autor) VALUES (77,'Ślęzak');
INSERT INTO autorstwo (Praca,Autor) VALUES (78,'Janusz');
INSERT INTO autorstwo (Praca,Autor) VALUES (79,'Karczmarz');
INSERT INTO autorstwo (Praca,Autor) VALUES (80,'Karczmarz');
INSERT INTO autorstwo (Praca,Autor) VALUES (80,'Sankowski');
INSERT INTO autorstwo (Praca,Autor) VALUES (81,'Karczmarz');
INSERT INTO autorstwo (Praca,Autor) VALUES (82,'Karczmarz');
INSERT INTO autorstwo (Praca,Autor) VALUES (83,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (83,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (83,'Waleń');
INSERT INTO autorstwo (Praca,Autor) VALUES (84,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (84,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (84,'Straszyński');
INSERT INTO autorstwo (Praca,Autor) VALUES (84,'Waleń');
INSERT INTO autorstwo (Praca,Autor) VALUES (85,'Charalampopoulos');
INSERT INTO autorstwo (Praca,Autor) VALUES (85,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (85,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (85,'Waleń');
INSERT INTO autorstwo (Praca,Autor) VALUES (86,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (86,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (86,'Waleń');
INSERT INTO autorstwo (Praca,Autor) VALUES (87,'Charalampopoulos');
INSERT INTO autorstwo (Praca,Autor) VALUES (87,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (87,'Straszyński');
INSERT INTO autorstwo (Praca,Autor) VALUES (88,'Kowalik');
INSERT INTO autorstwo (Praca,Autor) VALUES (88,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (88,'Wrochna');
INSERT INTO autorstwo (Praca,Autor) VALUES (89,'Lasota');
INSERT INTO autorstwo (Praca,Autor) VALUES (90,'Michalak');
INSERT INTO autorstwo (Praca,Autor) VALUES (91,'Gogacz');
INSERT INTO autorstwo (Praca,Autor) VALUES (91,'Murlak');
INSERT INTO autorstwo (Praca,Autor) VALUES (92,'Niemyska');
INSERT INTO autorstwo (Praca,Autor) VALUES (93,'Parys');
INSERT INTO autorstwo (Praca,Autor) VALUES (94,'Parys');
INSERT INTO autorstwo (Praca,Autor) VALUES (95,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (96,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (96,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (97,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (98,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (99,'Nadara');
INSERT INTO autorstwo (Praca,Autor) VALUES (99,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (100,'Gajarsky');
INSERT INTO autorstwo (Praca,Autor) VALUES (100,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (100,'Toruńczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (101,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (102,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (102,'Toruńczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (103,'Bojańczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (103,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (104,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (104,'Toruńczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (105,'Diks');
INSERT INTO autorstwo (Praca,Autor) VALUES (105,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (106,'Rządca');
INSERT INTO autorstwo (Praca,Autor) VALUES (107,'Rządca');
INSERT INTO autorstwo (Praca,Autor) VALUES (107,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (108,'Schmude');
INSERT INTO autorstwo (Praca,Autor) VALUES (109,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (110,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (111,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (112,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (113,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (114,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (115,'Skrzypczak');
INSERT INTO autorstwo (Praca,Autor) VALUES (116,'Skrzypczak');
INSERT INTO autorstwo (Praca,Autor) VALUES (117,'Janusz');
INSERT INTO autorstwo (Praca,Autor) VALUES (117,'Ślęzak');
INSERT INTO autorstwo (Praca,Autor) VALUES (118,'Ślęzak');
INSERT INTO autorstwo (Praca,Autor) VALUES (119,'Bojańczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (119,'Toruńczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (120,'Skibski');
INSERT INTO autorstwo (Praca,Autor) VALUES (121,'Skibski');
INSERT INTO autorstwo (Praca,Autor) VALUES (122,'Adamczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (122,'Włodarczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (123,'Biliński');
INSERT INTO autorstwo (Praca,Autor) VALUES (124,'Bojańczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (124,'Lhote');
INSERT INTO autorstwo (Praca,Autor) VALUES (125,'Bojańczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (125,'Klin');
INSERT INTO autorstwo (Praca,Autor) VALUES (126,'Bojańczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (126,'Skrzypczak');
INSERT INTO autorstwo (Praca,Autor) VALUES (127,'Bojańczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (127,'Kelmendi');
INSERT INTO autorstwo (Praca,Autor) VALUES (127,'Skrzypczak');
INSERT INTO autorstwo (Praca,Autor) VALUES (128,'Celińska-Kopczyńska');
INSERT INTO autorstwo (Praca,Autor) VALUES (129,'Clemente');
INSERT INTO autorstwo (Praca,Autor) VALUES (129,'Hofman');
INSERT INTO autorstwo (Praca,Autor) VALUES (130,'Clemente');
INSERT INTO autorstwo (Praca,Autor) VALUES (131,'Clemente');
INSERT INTO autorstwo (Praca,Autor) VALUES (131,'Lasota');
INSERT INTO autorstwo (Praca,Autor) VALUES (132,'Cygan');
INSERT INTO autorstwo (Praca,Autor) VALUES (132,'Mucha');
INSERT INTO autorstwo (Praca,Autor) VALUES (132,'Węgrzycki');
INSERT INTO autorstwo (Praca,Autor) VALUES (132,'Włodarczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (133,'Cygan');
INSERT INTO autorstwo (Praca,Autor) VALUES (133,'Kowalik');
INSERT INTO autorstwo (Praca,Autor) VALUES (134,'Cygan');
INSERT INTO autorstwo (Praca,Autor) VALUES (134,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (134,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (135,'Cygan');
INSERT INTO autorstwo (Praca,Autor) VALUES (135,'Mucha');
INSERT INTO autorstwo (Praca,Autor) VALUES (136,'Czerwiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (136,'Hofman');
INSERT INTO autorstwo (Praca,Autor) VALUES (136,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (137,'Czerwiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (137,'Lasota');
INSERT INTO autorstwo (Praca,Autor) VALUES (138,'Czerwiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (138,'Lasota');
INSERT INTO autorstwo (Praca,Autor) VALUES (139,'Czerwiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (139,'Lasota');
INSERT INTO autorstwo (Praca,Autor) VALUES (140,'Czerwiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (140,'Nadara');
INSERT INTO autorstwo (Praca,Autor) VALUES (140,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (141,'Diks');
INSERT INTO autorstwo (Praca,Autor) VALUES (141,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (142,'Dojer');
INSERT INTO autorstwo (Praca,Autor) VALUES (143,'Dunin-Kęplicz');
INSERT INTO autorstwo (Praca,Autor) VALUES (143,'Szałas');
INSERT INTO autorstwo (Praca,Autor) VALUES (144,'Dunin-Kęplicz');
INSERT INTO autorstwo (Praca,Autor) VALUES (144,'Szałas');
INSERT INTO autorstwo (Praca,Autor) VALUES (145,'Dunin-Kęplicz');
INSERT INTO autorstwo (Praca,Autor) VALUES (145,'Szałas');
INSERT INTO autorstwo (Praca,Autor) VALUES (146,'Dunin-Kęplicz');
INSERT INTO autorstwo (Praca,Autor) VALUES (147,'Dziembowski');
INSERT INTO autorstwo (Praca,Autor) VALUES (148,'Dziembowski');
INSERT INTO autorstwo (Praca,Autor) VALUES (149,'Dziembowski');
INSERT INTO autorstwo (Praca,Autor) VALUES (150,'Dziembowski');
INSERT INTO autorstwo (Praca,Autor) VALUES (151,'Fabiański');
INSERT INTO autorstwo (Praca,Autor) VALUES (151,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (151,'Toruńczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (152,'Chung');
INSERT INTO autorstwo (Praca,Autor) VALUES (152,'Gambin');
INSERT INTO autorstwo (Praca,Autor) VALUES (152,'Startek');
INSERT INTO autorstwo (Praca,Autor) VALUES (153,'Gambin');
INSERT INTO autorstwo (Praca,Autor) VALUES (153,'Jaworski');
INSERT INTO autorstwo (Praca,Autor) VALUES (154,'Gambin');
INSERT INTO autorstwo (Praca,Autor) VALUES (155,'Gambin');
INSERT INTO autorstwo (Praca,Autor) VALUES (156,'Chung');
INSERT INTO autorstwo (Praca,Autor) VALUES (156,'Gambin');
INSERT INTO autorstwo (Praca,Autor) VALUES (156,'Gogolewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (157,'Gambin');
INSERT INTO autorstwo (Praca,Autor) VALUES (157,'Startek');
INSERT INTO autorstwo (Praca,Autor) VALUES (158,'Gambin');
INSERT INTO autorstwo (Praca,Autor) VALUES (159,'Górecki');
INSERT INTO autorstwo (Praca,Autor) VALUES (160,'Górecki');
INSERT INTO autorstwo (Praca,Autor) VALUES (160,'Paszek');
INSERT INTO autorstwo (Praca,Autor) VALUES (161,'Górecki');
INSERT INTO autorstwo (Praca,Autor) VALUES (162,'Górecki');
INSERT INTO autorstwo (Praca,Autor) VALUES (163,'Hofman');
INSERT INTO autorstwo (Praca,Autor) VALUES (164,'Iwanicki');
INSERT INTO autorstwo (Praca,Autor) VALUES (165,'Kaliszyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (166,'Kaliszyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (167,'Kaliszyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (168,'Karczmarz');
INSERT INTO autorstwo (Praca,Autor) VALUES (169,'Karczmarz');
INSERT INTO autorstwo (Praca,Autor) VALUES (169,'Sankowski');
INSERT INTO autorstwo (Praca,Autor) VALUES (170,'Klin');
INSERT INTO autorstwo (Praca,Autor) VALUES (171,'Klin');
INSERT INTO autorstwo (Praca,Autor) VALUES (172,'Klin');
INSERT INTO autorstwo (Praca,Autor) VALUES (173,'Klin');
INSERT INTO autorstwo (Praca,Autor) VALUES (174,'Klin');
INSERT INTO autorstwo (Praca,Autor) VALUES (174,'Lasota');
INSERT INTO autorstwo (Praca,Autor) VALUES (174,'Toruńczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (175,'Kopczyński');
INSERT INTO autorstwo (Praca,Autor) VALUES (176,'Kowalik');
INSERT INTO autorstwo (Praca,Autor) VALUES (177,'Kowalik');
INSERT INTO autorstwo (Praca,Autor) VALUES (177,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (177,'Wrochna');
INSERT INTO autorstwo (Praca,Autor) VALUES (178,'Kowaluk');
INSERT INTO autorstwo (Praca,Autor) VALUES (179,'Kowaluk');
INSERT INTO autorstwo (Praca,Autor) VALUES (180,'Kozłowski');
INSERT INTO autorstwo (Praca,Autor) VALUES (181,'Michalak');
INSERT INTO autorstwo (Praca,Autor) VALUES (181,'Skibski');
INSERT INTO autorstwo (Praca,Autor) VALUES (182,'Michalak');
INSERT INTO autorstwo (Praca,Autor) VALUES (182,'Skibski');
INSERT INTO autorstwo (Praca,Autor) VALUES (183,'Michalak');
INSERT INTO autorstwo (Praca,Autor) VALUES (184,'Michalak');
INSERT INTO autorstwo (Praca,Autor) VALUES (185,'Michalak');
INSERT INTO autorstwo (Praca,Autor) VALUES (185,'Skibski');
INSERT INTO autorstwo (Praca,Autor) VALUES (186,'Michalak');
INSERT INTO autorstwo (Praca,Autor) VALUES (187,'Michalak');
INSERT INTO autorstwo (Praca,Autor) VALUES (188,'Mucha');
INSERT INTO autorstwo (Praca,Autor) VALUES (188,'Węgrzycki');
INSERT INTO autorstwo (Praca,Autor) VALUES (188,'Włodarczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (189,'Mucha');
INSERT INTO autorstwo (Praca,Autor) VALUES (189,'Pawlewicz');
INSERT INTO autorstwo (Praca,Autor) VALUES (189,'Węgrzycki');
INSERT INTO autorstwo (Praca,Autor) VALUES (190,'Murlak');
INSERT INTO autorstwo (Praca,Autor) VALUES (191,'Gogacz');
INSERT INTO autorstwo (Praca,Autor) VALUES (191,'Murlak');
INSERT INTO autorstwo (Praca,Autor) VALUES (192,'Górecki');
INSERT INTO autorstwo (Praca,Autor) VALUES (193,'Nguyen AL');
INSERT INTO autorstwo (Praca,Autor) VALUES (194,'Nguyen AL');
INSERT INTO autorstwo (Praca,Autor) VALUES (195,'Nguyen AL');
INSERT INTO autorstwo (Praca,Autor) VALUES (196,'Nguyen AL');
INSERT INTO autorstwo (Praca,Autor) VALUES (197,'Nguyen AL');
INSERT INTO autorstwo (Praca,Autor) VALUES (198,'Nguyen AL');
INSERT INTO autorstwo (Praca,Autor) VALUES (199,'Niemyska');
INSERT INTO autorstwo (Praca,Autor) VALUES (200,'Niemyska');
INSERT INTO autorstwo (Praca,Autor) VALUES (201,'Parys');
INSERT INTO autorstwo (Praca,Autor) VALUES (202,'Parys');
INSERT INTO autorstwo (Praca,Autor) VALUES (203,'Górecki');
INSERT INTO autorstwo (Praca,Autor) VALUES (203,'Paszek');
INSERT INTO autorstwo (Praca,Autor) VALUES (204,'Górecki');
INSERT INTO autorstwo (Praca,Autor) VALUES (204,'Paszek');
INSERT INTO autorstwo (Praca,Autor) VALUES (205,'Peczarski');
INSERT INTO autorstwo (Praca,Autor) VALUES (206,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (207,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (208,'Zych-Pawlewicz');
INSERT INTO autorstwo (Praca,Autor) VALUES (209,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (209,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (210,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (210,'Wrochna');
INSERT INTO autorstwo (Praca,Autor) VALUES (211,'Nadara');
INSERT INTO autorstwo (Praca,Autor) VALUES (211,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (212,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (213,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (214,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (214,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (215,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (215,'Sorge');
INSERT INTO autorstwo (Praca,Autor) VALUES (216,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (216,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (217,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (218,'Novotná');
INSERT INTO autorstwo (Praca,Autor) VALUES (218,'Okrasa');
INSERT INTO autorstwo (Praca,Autor) VALUES (218,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (218,'Rzążewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (219,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (219,'Wrochna');
INSERT INTO autorstwo (Praca,Autor) VALUES (220,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (221,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (222,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (223,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (223,'Wrochna');
INSERT INTO autorstwo (Praca,Autor) VALUES (224,'Przybyłek');
INSERT INTO autorstwo (Praca,Autor) VALUES (225,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (225,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (225,'Straszyński');
INSERT INTO autorstwo (Praca,Autor) VALUES (225,'Waleń');
INSERT INTO autorstwo (Praca,Autor) VALUES (226,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (226,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (226,'Straszyński');
INSERT INTO autorstwo (Praca,Autor) VALUES (226,'Waleń');
INSERT INTO autorstwo (Praca,Autor) VALUES (227,'Charalampopoulos');
INSERT INTO autorstwo (Praca,Autor) VALUES (227,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (227,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (227,'Straszyński');
INSERT INTO autorstwo (Praca,Autor) VALUES (227,'Waleń');
INSERT INTO autorstwo (Praca,Autor) VALUES (228,'Charalampopoulos');
INSERT INTO autorstwo (Praca,Autor) VALUES (228,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (228,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (228,'Straszyński');
INSERT INTO autorstwo (Praca,Autor) VALUES (228,'Waleń');
INSERT INTO autorstwo (Praca,Autor) VALUES (229,'Charalampopoulos');
INSERT INTO autorstwo (Praca,Autor) VALUES (229,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (230,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (231,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (232,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (233,'Charalampopoulos');
INSERT INTO autorstwo (Praca,Autor) VALUES (233,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (234,'Charalampopoulos');
INSERT INTO autorstwo (Praca,Autor) VALUES (234,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (234,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (234,'Waleń');
INSERT INTO autorstwo (Praca,Autor) VALUES (235,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (236,'Rządca');
INSERT INTO autorstwo (Praca,Autor) VALUES (237,'Sankowski');
INSERT INTO autorstwo (Praca,Autor) VALUES (238,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (239,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (240,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (241,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (242,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (243,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (244,'Chen');
INSERT INTO autorstwo (Praca,Autor) VALUES (244,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (244,'Sorge');
INSERT INTO autorstwo (Praca,Autor) VALUES (245,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (246,'Lhote');
INSERT INTO autorstwo (Praca,Autor) VALUES (246,'Michielini');
INSERT INTO autorstwo (Praca,Autor) VALUES (246,'Skrzypczak');
INSERT INTO autorstwo (Praca,Autor) VALUES (247,'Michalewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (247,'Skrzypczak');
INSERT INTO autorstwo (Praca,Autor) VALUES (248,'Ślęzak');
INSERT INTO autorstwo (Praca,Autor) VALUES (249,'Ślęzak');
INSERT INTO autorstwo (Praca,Autor) VALUES (250,'Ślęzak');
INSERT INTO autorstwo (Praca,Autor) VALUES (251,'Szałas');
INSERT INTO autorstwo (Praca,Autor) VALUES (252,'Szałas');
INSERT INTO autorstwo (Praca,Autor) VALUES (253,'Szczurek');
INSERT INTO autorstwo (Praca,Autor) VALUES (253,'Tiuryn');
INSERT INTO autorstwo (Praca,Autor) VALUES (254,'Szczurek');
INSERT INTO autorstwo (Praca,Autor) VALUES (255,'Tuszyńska');
INSERT INTO autorstwo (Praca,Autor) VALUES (255,'Wilczyński');
INSERT INTO autorstwo (Praca,Autor) VALUES (256,'Skibski');
INSERT INTO autorstwo (Praca,Autor) VALUES (257,'Węgrzycki');
INSERT INTO autorstwo (Praca,Autor) VALUES (258,'Wilczyński');
INSERT INTO autorstwo (Praca,Autor) VALUES (259,'Włodarczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (260,'Włodarczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (261,'Adamczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (261,'Włodarczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (262,'Iwanicki');
INSERT INTO autorstwo (Praca,Autor) VALUES (263,'Biliński');
INSERT INTO autorstwo (Praca,Autor) VALUES (264,'Biliński');
INSERT INTO autorstwo (Praca,Autor) VALUES (265,'Bojańczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (265,'Kelmendi');
INSERT INTO autorstwo (Praca,Autor) VALUES (265,'Stefański');
INSERT INTO autorstwo (Praca,Autor) VALUES (266,'Bojańczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (267,'Bojańczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (267,'Stefański');
INSERT INTO autorstwo (Praca,Autor) VALUES (268,'Bojańczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (268,'Schmude');
INSERT INTO autorstwo (Praca,Autor) VALUES (269,'Bojańczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (270,'Cygan');
INSERT INTO autorstwo (Praca,Autor) VALUES (271,'Cygan');
INSERT INTO autorstwo (Praca,Autor) VALUES (271,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (272,'Czerwiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (273,'Czerwiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (273,'Lasota');
INSERT INTO autorstwo (Praca,Autor) VALUES (274,'Czerwiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (274,'Hofman');
INSERT INTO autorstwo (Praca,Autor) VALUES (275,'Dojer');
INSERT INTO autorstwo (Praca,Autor) VALUES (276,'Dutta');
INSERT INTO autorstwo (Praca,Autor) VALUES (277,'Dziubiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (278,'Dziubiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (279,'Fleszar');
INSERT INTO autorstwo (Praca,Autor) VALUES (280,'Fleszar');
INSERT INTO autorstwo (Praca,Autor) VALUES (281,'Gambin');
INSERT INTO autorstwo (Praca,Autor) VALUES (281,'Gogolewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (282,'Gambin');
INSERT INTO autorstwo (Praca,Autor) VALUES (282,'Startek');
INSERT INTO autorstwo (Praca,Autor) VALUES (283,'Gambin');
INSERT INTO autorstwo (Praca,Autor) VALUES (284,'Gambin');
INSERT INTO autorstwo (Praca,Autor) VALUES (285,'Gora');
INSERT INTO autorstwo (Praca,Autor) VALUES (286,'Górecki');
INSERT INTO autorstwo (Praca,Autor) VALUES (287,'Górecki');
INSERT INTO autorstwo (Praca,Autor) VALUES (287,'Paszek');
INSERT INTO autorstwo (Praca,Autor) VALUES (287,'Tiuryn');
INSERT INTO autorstwo (Praca,Autor) VALUES (288,'Hofman');
INSERT INTO autorstwo (Praca,Autor) VALUES (289,'Iwanicki');
INSERT INTO autorstwo (Praca,Autor) VALUES (290,'Janusz');
INSERT INTO autorstwo (Praca,Autor) VALUES (290,'Ślęzak');
INSERT INTO autorstwo (Praca,Autor) VALUES (291,'Charalampopoulos');
INSERT INTO autorstwo (Praca,Autor) VALUES (291,'Karczmarz');
INSERT INTO autorstwo (Praca,Autor) VALUES (292,'Kołodziejski');
INSERT INTO autorstwo (Praca,Autor) VALUES (293,'Kowalik');
INSERT INTO autorstwo (Praca,Autor) VALUES (293,'Li');
INSERT INTO autorstwo (Praca,Autor) VALUES (293,'Nadara');
INSERT INTO autorstwo (Praca,Autor) VALUES (293,'Smulewicz');
INSERT INTO autorstwo (Praca,Autor) VALUES (294,'Kowalik');
INSERT INTO autorstwo (Praca,Autor) VALUES (294,'Majewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (295,'Kowalik');
INSERT INTO autorstwo (Praca,Autor) VALUES (295,'Mucha');
INSERT INTO autorstwo (Praca,Autor) VALUES (295,'Nadara');
INSERT INTO autorstwo (Praca,Autor) VALUES (295,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (295,'Sorge');
INSERT INTO autorstwo (Praca,Autor) VALUES (295,'Wygocki');
INSERT INTO autorstwo (Praca,Autor) VALUES (296,'Kowaluk');
INSERT INTO autorstwo (Praca,Autor) VALUES (297,'Kozłowski');
INSERT INTO autorstwo (Praca,Autor) VALUES (298,'Lasota');
INSERT INTO autorstwo (Praca,Autor) VALUES (299,'Machnicka');
INSERT INTO autorstwo (Praca,Autor) VALUES (300,'Michalak');
INSERT INTO autorstwo (Praca,Autor) VALUES (300,'Skibski');
INSERT INTO autorstwo (Praca,Autor) VALUES (301,'Michalak');
INSERT INTO autorstwo (Praca,Autor) VALUES (302,'Michalak');
INSERT INTO autorstwo (Praca,Autor) VALUES (303,'Michalak');
INSERT INTO autorstwo (Praca,Autor) VALUES (303,'Skibski');
INSERT INTO autorstwo (Praca,Autor) VALUES (304,'Michalak');
INSERT INTO autorstwo (Praca,Autor) VALUES (304,'Skibski');
INSERT INTO autorstwo (Praca,Autor) VALUES (305,'Michalak');
INSERT INTO autorstwo (Praca,Autor) VALUES (306,'Mucha');
INSERT INTO autorstwo (Praca,Autor) VALUES (306,'Smulewicz');
INSERT INTO autorstwo (Praca,Autor) VALUES (307,'Gogacz');
INSERT INTO autorstwo (Praca,Autor) VALUES (307,'Murlak');
INSERT INTO autorstwo (Praca,Autor) VALUES (308,'Gogacz');
INSERT INTO autorstwo (Praca,Autor) VALUES (308,'Murlak');
INSERT INTO autorstwo (Praca,Autor) VALUES (309,'Nguyen AL');
INSERT INTO autorstwo (Praca,Autor) VALUES (310,'Nguyen AL');
INSERT INTO autorstwo (Praca,Autor) VALUES (311,'Niemyska');
INSERT INTO autorstwo (Praca,Autor) VALUES (312,'Niemyska');
INSERT INTO autorstwo (Praca,Autor) VALUES (313,'Niwiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (313,'Skrzypczak');
INSERT INTO autorstwo (Praca,Autor) VALUES (314,'Niwiński');
INSERT INTO autorstwo (Praca,Autor) VALUES (314,'Parys');
INSERT INTO autorstwo (Praca,Autor) VALUES (315,'Parys');
INSERT INTO autorstwo (Praca,Autor) VALUES (316,'Parys');
INSERT INTO autorstwo (Praca,Autor) VALUES (317,'Barozzini');
INSERT INTO autorstwo (Praca,Autor) VALUES (317,'Clemente');
INSERT INTO autorstwo (Praca,Autor) VALUES (317,'Parys');
INSERT INTO autorstwo (Praca,Autor) VALUES (318,'Parys');
INSERT INTO autorstwo (Praca,Autor) VALUES (319,'Parys');
INSERT INTO autorstwo (Praca,Autor) VALUES (320,'Parys');
INSERT INTO autorstwo (Praca,Autor) VALUES (321,'Parys');
INSERT INTO autorstwo (Praca,Autor) VALUES (322,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (322,'Sorge');
INSERT INTO autorstwo (Praca,Autor) VALUES (323,'Bellitto');
INSERT INTO autorstwo (Praca,Autor) VALUES (323,'Li');
INSERT INTO autorstwo (Praca,Autor) VALUES (323,'Okrasa');
INSERT INTO autorstwo (Praca,Autor) VALUES (323,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (323,'Sorge');
INSERT INTO autorstwo (Praca,Autor) VALUES (324,'Li');
INSERT INTO autorstwo (Praca,Autor) VALUES (324,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (325,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (325,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (326,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (326,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (327,'Pilipczuk Ma');
INSERT INTO autorstwo (Praca,Autor) VALUES (328,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (328,'Węgrzycki');
INSERT INTO autorstwo (Praca,Autor) VALUES (329,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (330,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (331,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (332,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (333,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (334,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (335,'Gajarský');
INSERT INTO autorstwo (Praca,Autor) VALUES (335,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (335,'Toruńczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (336,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (337,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (338,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (339,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (340,'Pilipczuk Mi');
INSERT INTO autorstwo (Praca,Autor) VALUES (340,'Wrochna');
INSERT INTO autorstwo (Praca,Autor) VALUES (341,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (341,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (341,'Waleń');
INSERT INTO autorstwo (Praca,Autor) VALUES (342,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (343,'Charalampopoulos');
INSERT INTO autorstwo (Praca,Autor) VALUES (343,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (343,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (343,'Straszyński');
INSERT INTO autorstwo (Praca,Autor) VALUES (343,'Waleń');
INSERT INTO autorstwo (Praca,Autor) VALUES (344,'Charalampopoulos');
INSERT INTO autorstwo (Praca,Autor) VALUES (344,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (345,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (345,'Straszyński');
INSERT INTO autorstwo (Praca,Autor) VALUES (346,'Charalampopoulos');
INSERT INTO autorstwo (Praca,Autor) VALUES (346,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (346,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (346,'Waleń');
INSERT INTO autorstwo (Praca,Autor) VALUES (347,'Charalampopoulos');
INSERT INTO autorstwo (Praca,Autor) VALUES (347,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (348,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (349,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (349,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (349,'Straszyński');
INSERT INTO autorstwo (Praca,Autor) VALUES (349,'Waleń');
INSERT INTO autorstwo (Praca,Autor) VALUES (350,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (350,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (350,'Straszyński');
INSERT INTO autorstwo (Praca,Autor) VALUES (350,'Waleń');
INSERT INTO autorstwo (Praca,Autor) VALUES (351,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (352,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (352,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (352,'Waleń');
INSERT INTO autorstwo (Praca,Autor) VALUES (353,'Charalampopoulos');
INSERT INTO autorstwo (Praca,Autor) VALUES (353,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (353,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (353,'Waleń');
INSERT INTO autorstwo (Praca,Autor) VALUES (354,'Charalampopoulos');
INSERT INTO autorstwo (Praca,Autor) VALUES (354,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (354,'Waleń');
INSERT INTO autorstwo (Praca,Autor) VALUES (355,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (355,'Rytter');
INSERT INTO autorstwo (Praca,Autor) VALUES (355,'Waleń');
INSERT INTO autorstwo (Praca,Autor) VALUES (356,'Radoszewski');
INSERT INTO autorstwo (Praca,Autor) VALUES (357,'Rządca');
INSERT INTO autorstwo (Praca,Autor) VALUES (358,'Rządca');
INSERT INTO autorstwo (Praca,Autor) VALUES (359,'Schmude');
INSERT INTO autorstwo (Praca,Autor) VALUES (360,'Skibski');
INSERT INTO autorstwo (Praca,Autor) VALUES (361,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (362,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (363,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (364,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (365,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (366,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (367,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (368,'Skowron');
INSERT INTO autorstwo (Praca,Autor) VALUES (369,'Skrzypczak');
INSERT INTO autorstwo (Praca,Autor) VALUES (370,'Michielini');
INSERT INTO autorstwo (Praca,Autor) VALUES (370,'Skrzypczak');
INSERT INTO autorstwo (Praca,Autor) VALUES (371,'Fabiański');
INSERT INTO autorstwo (Praca,Autor) VALUES (371,'Skrzypczak');
INSERT INTO autorstwo (Praca,Autor) VALUES (371,'Toruńczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (372,'Ślęzak');
INSERT INTO autorstwo (Praca,Autor) VALUES (373,'Ślęzak');
INSERT INTO autorstwo (Praca,Autor) VALUES (374,'Ślęzak');
INSERT INTO autorstwo (Praca,Autor) VALUES (375,'Ślęzak');
INSERT INTO autorstwo (Praca,Autor) VALUES (376,'Ślęzak');
INSERT INTO autorstwo (Praca,Autor) VALUES (377,'Ślęzak');
INSERT INTO autorstwo (Praca,Autor) VALUES (378,'Startek');
INSERT INTO autorstwo (Praca,Autor) VALUES (379,'Startek');
INSERT INTO autorstwo (Praca,Autor) VALUES (380,'Szałas');
INSERT INTO autorstwo (Praca,Autor) VALUES (381,'Szałas');
INSERT INTO autorstwo (Praca,Autor) VALUES (382,'Szałas');
INSERT INTO autorstwo (Praca,Autor) VALUES (383,'Szczurek');
INSERT INTO autorstwo (Praca,Autor) VALUES (384,'Szczurek');
INSERT INTO autorstwo (Praca,Autor) VALUES (385,'Szczurek');
INSERT INTO autorstwo (Praca,Autor) VALUES (386,'Górecki');
INSERT INTO autorstwo (Praca,Autor) VALUES (386,'Tiuryn');
INSERT INTO autorstwo (Praca,Autor) VALUES (387,'Toruńczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (388,'Toruńczyk');
INSERT INTO autorstwo (Praca,Autor) VALUES (389,'Wilczyński');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Adamczyk',1,'2,4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Barozzini',1,'1,6');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Bellitto',0,'1,6');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Biecek',0,'1,78');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Biliński',1,'3,2');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Bojańczyk',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Celińska-Kopczyńska',0,'2,4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Charalampopoulos',0,'1');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Chen',0,'1');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Chengot Sankaramenon',0,'1,6');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Chung',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Clemente',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Cygan',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Cyranka',0,'2,4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Czerwiński',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Darvish Shafighi',1,'2,4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Defrain',0,'1');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Diks',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Dojer',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Dross',0,'1');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Dunin-Kęplicz',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Dutta',0,'2,4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Dziembowski',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Dziubiński',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Fabiański',0,'1,64');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Fleszar',1,'2,4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Gajarský',0,'1');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Gambin',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Geniet',0,'1');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Gogacz',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Gogolewski',0,'1,76');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Gora',0,'1,6');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Górecki',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Hofman',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Iwanicki',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Jankowski',0,'1,6');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Janusz',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Jaworski',1,'2,4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Kaliszyk',1,'1');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Kang',1,'2,4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Karczmarz',1,'2,08');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Kazana',1,'2');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Kelmendi',0,'1');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Kiefer',0,'1');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Klin',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Kołodziejski',1,'2,4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Kopczyński',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Kowalik',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Kowaluk',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Kozłowski',1,'3,2');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Lasota',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Lhote',0,'1,6');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Li',1,'3,2');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Machnicka',1,'3,2');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Majewski',0,'1,44');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Mari',0,'1');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Masařik',0,'1,6');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Michalak',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Michalewski',1,'1,25');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Michielini',1,'3,2');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Mucha',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Mukherjee',0,'1,6');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Murlak',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Muzi',0,'1,6');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Nadara',1,'2,4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Nguyen AL',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Nguyen HS',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Niemyska',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Niwiński',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Novotná',0,'2,4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Nyporko',0,'1');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Odrzygóźdź',0,'1');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Okrasa',0,'2,4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Pacuk',0,'2');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Parys',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Paszek',0,'1,6');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Pawlewicz',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Pilipczuk Ma',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Pilipczuk Mi',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Plandowski',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Pratt-Hartmann',0,'1');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Przybylski',0,'1,6');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Przybyłek',1,'2,4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Radoszewski',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Rosa',0,'1');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Rutka',0,'1,6');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Rytter',1,'2');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Rządca',1,'3,2');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Rzążewski',0,'1');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Salamanca Tellez',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Sankowski',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Schmude',1,'3,2');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Schubert',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Skibski',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Skowron',1,'3,2');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Skrzypczak',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Smulewicz',1,'3,2');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Sokołowski',0,'1,44');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Sorge',0,'1,6');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Sroka',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Startek',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Stefański',0,'1,6');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Stencel',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Straszyński',0,'1');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Szałas',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Szczurek',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Ślęzak',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Tarlecki',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Tempczyk',0,'1,4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Tiuryn',1,'3,2');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Toruńczyk',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Tuszyńska',1,'3,2');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Tyszkiewicz',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Urzyczyn',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Vigny',0,'1');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Waleń',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Wasilewski',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Węgrzycki',1,'2,88');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Wilczyński',1,'4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Witkowski',0,'2,4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Włodarczyk',1,'2,32');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Wrochna',0,'1');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Wygocki',1,'2,4');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Zanka',0,'1');
INSERT INTO autorzy (ID,Ryzyko,Sloty) VALUES ('Zych-Pawlewicz',1,'4');

-- Zapytanie
WITH pilipczuk(autor_path, praca_path, Praca, Autor, LiczbaPilipczuka) AS (
    SELECT
        CAST(Autor AS VARCHAR(1000)),
        CAST(Praca AS VARCHAR(1000)),
        Praca,
        Autor,
        0
    FROM autorstwo
    WHERE Autor = 'Pilipczuk Mi'
    UNION ALL
    SELECT 
        pilipczuk.autor_path || '-' || autorstwo.Autor,
        pilipczuk.praca_path || '-' || autorstwo.Praca,
        autorstwo.Praca, 
        autorstwo.Autor,
        pilipczuk.LiczbaPilipczuka + CASE 
            WHEN autorstwo.Autor != pilipczuk.Autor THEN 1
            ELSE 0
        END
    FROM autorstwo, pilipczuk
    WHERE (INSTR(pilipczuk.autor_path, autorstwo.Autor) = 0 AND autorstwo.Praca = pilipczuk.Praca) OR ((INSTR(pilipczuk.praca_path, autorstwo.Praca) = 0) AND (autorstwo.Autor = pilipczuk.Autor))
), pilipczuk_records (Autor, LiczbaPilipczuka) AS (
    SELECT Autor, MIN(LiczbaPilipczuka)
    FROM pilipczuk
    GROUP BY Autor
)
SELECT 
    ID,
    LiczbaPilipczuka
FROM autorzy
LEFT JOIN pilipczuk_records ON Autor = ID;

DROP TABLE autorstwo;
DROP TABLE autorzy;