CREATE TABLE Czlowiek (
    PESEL CHAR(11) PRIMARY KEY,
    Imie VARCHAR2(50) NOT NULL,
    Nazwisko VARCHAR2(50) NOT NULL
);

CREATE TABLE Mieszkanie (
    Adres VARCHAR2(255) PRIMARY KEY,
    Metraz NUMBER(10, 2) NOT NULL,
    PESEL_Wlasciciela CHAR(11) NOT NULL REFERENCES Czlowiek(PESEL)
);

CREATE TABLE Rezydencja (
    PESEL CHAR(11) NOT NULL UNIQUE REFERENCES Czlowiek(PESEL),
    Adres VARCHAR2(255) NOT NULL REFERENCES Mieszkanie(Adres),
    CONSTRAINT PK_Rezydencja PRIMARY KEY (PESEL, Adres)
);